services:
  CloudBackendDb:
    image: postgres:18-alpine
    restart: unless-stopped
    container_name: "nfcclouddb"
    ports:
      - 5532:5432
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=clouddb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  CloudBackendDbPgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - CloudBackendDb
    ports:
      - 8084:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@local.com
      - PGADMIN_DEFAULT_PASSWORD=root

volumes:
  pgdata: